import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import 'amfe-flexible'
import 'vant/lib/index.css'
import { Search, Uploader, ActionBar, ActionBarIcon, ActionBarButton, PullRefresh, List, Loading, Grid, GridItem, Popup, Overlay, ContactCard, AddressEdit, AddressList, Cell, ActionSheet, Empty, Stepper, Checkbox, CheckboxGroup, SwipeCell, SubmitBar, Form, Field, CellGroup, Tag, Button, Image, Swipe, SwipeItem, Sidebar, SidebarItem, Lazyload, Badge, Collapse, CollapseItem, Tab, Tabs, Card } from 'vant'
createApp(App)
  .use(Swipe)
  .use(Search)
  .use(Uploader)
  .use(ActionBar)
  .use(ActionBarIcon)
  .use(ActionBarButton)
  .use(List)
  .use(PullRefresh)
  .use(Grid)
  .use(Loading)
  .use(GridItem)
  .use(Popup)
  .use(Overlay)
  .use(ContactCard)
  .use(AddressEdit)
  .use(Cell)
  .use(AddressList)
  .use(ActionSheet)
  .use(Empty)
  .use(Stepper)
  .use(Checkbox)
  .use(CheckboxGroup)
  .use(SwipeCell)
  .use(SubmitBar)
  .use(Form)
  .use(CellGroup)
  .use(Field)
  .use(SwipeItem)
  .use(Sidebar)
  .use(SidebarItem)
  .use(Collapse)
  .use(CollapseItem)
  .use(Tab)
  .use(Tag)
  .use(Button)
  .use(Tabs)
  .use(Card)
  .use(Badge)
  .use(Image)
  .use(Lazyload, {
    loading: require('assets/image/logo375160.png')
  })
  .use(store)
  .use(router)
  .mount('#app')
